name: Deploy Svelte to Fly.io (Monorepo)

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**' # Only trigger if changes are in the 'frontend' folder

jobs:
  deploy:
    name: Deploy frontend app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only -a fly-frontend # Explicitly specify app name
        working-directory: ./frontend # Tell flyctl to run from the frontend directory
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}