# .github/workflows/deploy-backend.yml
name: Deploy FastAPI to Fly.io (Monorepo)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Only trigger if changes are in the 'backend' folder

jobs:
  deploy:
    name: Deploy backend app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only -a fly-backend1 # Explicitly specify app name
        working-directory: ./backend # Tell flyctl to run from the backend directory
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}